# Generated by Django 4.1.3 on 2022-11-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('parent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('status', models.IntegerField()),
                ('dateplaceorder', models.DateTimeField()),
                ('datecomplete', models.DateTimeField()),
                ('orderaddress', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('image', models.CharField(max_length=255)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.category')),
            ],
            options={
                'db_table': 'product',
                'unique_together': {('idproduct', 'image')},
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('discountvalue', models.FloatField()),
                ('discountunit', models.CharField(max_length=20)),
                ('createdate', models.DateTimeField()),
                ('from_field', models.DateTimeField()),
                ('until', models.DateTimeField()),
                ('couponcode', models.CharField(max_length=10)),
                ('minimumordervalue', models.FloatField()),
                ('is_redeem_allowed', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
            options={
                'db_table': 'product_discount',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('idpricing', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('date_expiry', models.DateTimeField()),
                ('in_active', models.IntegerField()),
                ('baseprice', models.CharField(blank=True, max_length=45, null=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
            options={
                'db_table': 'pricing',
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('detailsid', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.order')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
            options={
                'db_table': 'orderdetails',
            },
        ),
    ]
