# Generated by Django 4.1.3 on 2022-11-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='idproduct',
            new_name='productid',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('productid', 'image')},
        ),
    ]
