# Generated by Django 4.1.3 on 2022-11-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datecomplete',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateplaceorder',
            field=models.DateTimeField(default='2022-11-18T14:31:19Z'),
        ),
    ]
