# Generated by Django 4.1.3 on 2022-11-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_datecomplete_alter_order_dateplaceorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datecomplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateplaceorder',
            field=models.DateTimeField(default='2022-11-18T14:34:29Z'),
        ),
    ]
