# Generated by Django 4.1.3 on 2022-11-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_dateplaceorder_alter_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateplaceorder',
            field=models.DateTimeField(default='2022-11-18T15:03:23Z'),
        ),
    ]
